name: Roster Integration Workflow

on:
  pull_request:
    branches:
      - main
      - 'release-**.x'

env:
  HEADLESS_MODE: 'true'

permissions:
  id-token: write   # This is required for requesting the JWT

jobs:
  integ-roster:
    name: Roster Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Package
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_SDK_DEV }}
          role-session-name: integ-test
          aws-region: us-east-1
      - name: Clean Install
        run: npm ci
      - name: Run Roster Integration Test in Headless Chrome
        run: |
          cd integration
          npm install
          npm run test -- --test=roster --host=chrome
